display: Add missing assert.h
On initial  Android-15-ap3a, The build was failing with the following error:

[1mhardware/qcom-caf/sm6225/display/composer/hwc_buffer_sync_handler.cpp:112:3: [0m[0;1;31merror: [0m[1muse of undeclared identifier 'assert'[0m
  112 |   assert(false);[0m
      | [0;1;32m  ^
[0m[1mhardware/qcom-caf/sm6225/display/composer/hwc_buffer_sync_handler.cpp:118:3: [0m[0;1;31merror: [0m[1muse of undeclared identifier 'assert'[0m
  118 |   assert(false);[0m
      | [0;1;32m  ^